### ISSUE TITLE
Unable to change `Id` column name

### ISSUE THREAD

**Issue by forrestab** [lucascebertin/Serilog.Sinks.Oracle#2]
I am not sure if its intended, but I would like to change the column name for `Id`. I started by just changing the name via the `columnOptions` argument, but that is throwing an exception.

```js
// appsettings.json

"Args": {
    "columnOptions": {
        "id": { "ColumnName": "MESSAGE_ID" } // `MESSAGE_ID` in the db also
    }
}
```

> Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-01722: invalid number
   at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteNonQuery(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteNonQuery()
   at System.Data.Common.DbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at Serilog.Sinks.Oracle.Database.StoreLogAsync(IEnumerable`1 events)
   
It seems the function is not being executed if the column name is changed both for the sink and db. It may have something to do with how `Id` is specially treated [here](https://github.com/lucascebertin/Serilog.Sinks.Oracle/blob/master/src/Serilog.Sinks.Oracle/Serilog.Sinks.Oracle/Database.cs#L51) and [here](https://github.com/lucascebertin/Serilog.Sinks.Oracle/blob/master/src/Serilog.Sinks.Oracle/Serilog.Sinks.Oracle/Database.cs#L56) or it could be that I am doing something wrong, any help would be appreciated.

**Comment by lucascebertin** [comment]
Hey, I'll look that on this week and get back with an answer!

**Comment by bduman** [comment]
You got this error because of some hard coded values in OracleDatabaseBatchSink.cs [[1](https://github.com/lucascebertin/Serilog.Sinks.Oracle/blob/7156397b45112363970450578f8cc1de020c57b9/src/Serilog.Sinks.Oracle/Serilog.Sinks.Oracle/Core/OracleDatabaseBatchSink.cs#L141)/[2](https://github.com/lucascebertin/Serilog.Sinks.Oracle/blob/7156397b45112363970450578f8cc1de020c57b9/src/Serilog.Sinks.Oracle/Serilog.Sinks.Oracle/Core/OracleDatabaseBatchSink.cs#L146)]

That code block prepare sql to bindable column names except "Id". So program executed something like INSERT ... VALUES ('FUNC_NAME', .. Then you have got invalid number error.
Sql preparation should be dynamic reading from _columnOptions.
