### ISSUE TITLE
Unable to customize stored columns

### ISSUE THREAD

**Issue by forrestab** [lucascebertin/Serilog.Sinks.Oracle#3]
I am trying avoid storing certain columns in the db (i.e. `MessageTemplate`) and was looking for something similar to the MSSQL sink's `removeStandardColumns` configuration. I noticed the `ColumnOptions.Store` property and hoped that all I had to do was provide the standard columns that I wanted stored based on the properties [`set` logic](https://github.com/lucascebertin/Serilog.Sinks.Oracle/blob/master/src/Serilog.Sinks.Oracle/Serilog.Sinks.Oracle/Columns/ColumnOptions.cs#L56), but in doing so it throws this exception:

>System.Data.DuplicateNameException: A column named 'MESSAGE' already belongs to this DataTable.
   at System.Data.DataColumnCollection.RegisterColumnName(String name, DataColumn column)
   at System.Data.DataColumnCollection.BaseAdd(DataColumn column)
   at System.Data.DataColumnCollection.AddAt(Int32 index, DataColumn column)
   at Serilog.Sinks.Oracle.Database.CreateDataTable()
   at Serilog.Sinks.Oracle.Database.FillDataTable(IEnumerable`1 events)
   at Serilog.Sinks.Oracle.Database.StoreLogAsync(IEnumerable`1 events)The program '[34640] iisexpress.exe' has exited with code -1 (0xffffffff).

Am I trying to use this incorrectly?

**Comment by lucascebertin** [comment]
Hey, I'll look that on this week and get back with an answer!
